#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# build.py
# Produces the installable Blender addon zip and the Houdini package directory.
#
# Usage:
#   python build.py               -- build both targets
#   python build.py --blender     -- Blender zip only
#   python build.py --houdini     -- Houdini package only (stubs for Phase 2+)
#
# Output:
#   dist/ylos_blender_vX.Y.Z.zip  -- drop-install for Blender
#   dist/ylos_houdini/            -- copy to $HOUDINI_USER_PREF_DIR/packages/
#                                    (Phase 2, not produced yet)
#
# The key operation is vendoring: ylos_core is copied into
# ylos_blender/_vendor/ylos_core before zipping. The _vendor directory is
# git-ignored (never committed) and rebuilt fresh on every build.

import sys
import shutil
import zipfile
import argparse
from pathlib import Path

REPO_ROOT   = Path(__file__).parent.resolve()
CORE_SRC    = REPO_ROOT / "ylos_core"
BLENDER_SRC = REPO_ROOT / "ylos_blender"
VENDOR_DST  = BLENDER_SRC / "_vendor" / "ylos_core"
DIST_DIR    = REPO_ROOT / "dist"

# Read version from bl_info without importing bpy
def _read_version() -> str:
    init = (BLENDER_SRC / "__init__.py").read_text(encoding="utf-8")
    for line in init.splitlines():
        if '"version"' in line and "(" in line:
            # e.g.   "version": (0, 3, 0),
            nums = [c for c in line if c.isdigit()]
            if len(nums) >= 3:
                return f"{nums[0]}.{nums[1]}.{nums[2]}"
    return "0.0.0"


def vendor_core() -> None:
    """Copy ylos_core into ylos_blender/_vendor/ylos_core (fresh each time)."""
    print(f"  Vendoring {CORE_SRC} -> {VENDOR_DST}")
    if VENDOR_DST.exists():
        shutil.rmtree(VENDOR_DST)
    shutil.copytree(CORE_SRC, VENDOR_DST)
    # Write a sentinel so the vendor dir is recognisable
    (VENDOR_DST.parent / "_VENDORED").write_text(
        "This directory is auto-generated by build.py. Do not edit.\n"
    )


def build_blender_zip() -> Path:
    """
    Zip ylos_blender/ into a Blender-installable addon zip.

    The zip contains ylos_blender/ at its root (Blender expects the top-level
    directory to match the addon package name when installing from zip).
    """
    version = _read_version()
    zip_name = f"ylos_blender_v{version}.zip"
    zip_path = DIST_DIR / zip_name

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    if zip_path.exists():
        zip_path.unlink()

    excluded_dirs  = {"__pycache__", ".git"}
    excluded_files = {".DS_Store", "Thumbs.db"}

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(BLENDER_SRC.rglob("*")):
            # Skip excluded dirs and their contents
            if any(part in excluded_dirs for part in file.parts):
                continue
            if file.name in excluded_files:
                continue
            if file.is_file():
                arcname = "ylos_blender" / file.relative_to(BLENDER_SRC)
                zf.write(file, arcname)

    print(f"  Built: {zip_path}  ({zip_path.stat().st_size // 1024} KB)")
    return zip_path


def build_houdini_package() -> None:
    """Stub -- Phase 2. Produces ylos_houdini/ directory."""
    houdini_src = REPO_ROOT / "ylos_houdini"
    if not houdini_src.exists():
        print("  ylos_houdini/ not yet created -- skipping (Phase 2)")
        return
    # Phase 2: vendor core into ylos_houdini/pythonlibs/ylos_core
    # and copy the package to dist/ylos_houdini/
    print("  Houdini package build not yet implemented (Phase 2)")


def main():
    parser = argparse.ArgumentParser(description="Ylos Pipeline build script")
    parser.add_argument("--blender",  action="store_true", help="Build Blender zip only")
    parser.add_argument("--houdini",  action="store_true", help="Build Houdini package only")
    args = parser.parse_args()

    do_blender = args.blender or (not args.blender and not args.houdini)
    do_houdini = args.houdini or (not args.blender and not args.houdini)

    print("=== Ylos Pipeline Build ===")

    print("[1/2] Vendoring ylos_core...")
    vendor_core()

    if do_blender:
        print("[2/2] Building Blender zip...")
        zip_path = build_blender_zip()
        print(f"\nBlender addon ready: {zip_path}")
        print("Install via: Edit > Preferences > Add-ons > Install Legacy Add-on...")

    if do_houdini:
        print("[2/2] Building Houdini package...")
        build_houdini_package()

    print("\nDone.")


if __name__ == "__main__":
    main()
