#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# build.py
# Produces the installable Blender addon zip and the Houdini package directory.
#
# Usage:
#   python build.py               -- build both targets
#   python build.py --blender     -- Blender zip only
#   python build.py --houdini     -- Houdini package only (stubs for Phase 2+)
#
# Output:
#   dist/ylos_blender_vX.Y.Z.zip  -- drop-install for Blender
#   dist/ylos_houdini/            -- copy to $HOUDINI_USER_PREF_DIR/packages/
#                                    (Phase 2, not produced yet)
#
# The key operation is vendoring: ylos_core is copied into
# ylos_blender/_vendor/ylos_core before zipping. The _vendor directory is
# git-ignored (never committed) and rebuilt fresh on every build.

import sys
import shutil
import zipfile
import hashlib
import argparse
from datetime import datetime
from pathlib import Path

REPO_ROOT   = Path(__file__).parent.resolve()
CORE_SRC    = REPO_ROOT / "ylos_core"
BLENDER_SRC = REPO_ROOT / "ylos_blender"
VENDOR_DST  = BLENDER_SRC / "_vendor" / "ylos_core"
DIST_DIR    = REPO_ROOT / "dist"

# Read version from bl_info without importing bpy
def _read_version() -> str:
    init = (BLENDER_SRC / "__init__.py").read_text(encoding="utf-8")
    for line in init.splitlines():
        if '"version"' in line and "(" in line:
            # e.g.   "version": (0, 3, 0),
            nums = [c for c in line if c.isdigit()]
            if len(nums) >= 3:
                return f"{nums[0]}.{nums[1]}.{nums[2]}"
    return "0.0.0"


def _hash_tree(src: Path) -> str:
    """SHA-256 of all .py files in src (sorted), truncated to 16 hex chars."""
    h = hashlib.sha256()
    for f in sorted(src.rglob("*.py")):
        h.update(f.read_bytes())
    return h.hexdigest()[:16]


def vendor_core() -> None:
    """Copy ylos_core into ylos_blender/_vendor/ylos_core (fresh each time)."""
    print(f"  Vendoring {CORE_SRC} -> {VENDOR_DST}")
    if VENDOR_DST.exists():
        shutil.rmtree(VENDOR_DST)
    shutil.copytree(CORE_SRC, VENDOR_DST)
    (VENDOR_DST.parent / "_VENDORED").write_text(
        f"Auto-generated by build.py. Do not edit.\n"
        f"hash={_hash_tree(CORE_SRC)}\n"
        f"built={datetime.now().isoformat()}\n"
    )


def build_blender_zip() -> Path:
    """
    Zip ylos_blender/ into a Blender-installable addon zip.

    The zip contains ylos_blender/ at its root (Blender expects the top-level
    directory to match the addon package name when installing from zip).
    """
    version = _read_version()
    zip_name = f"ylos_blender_v{version}.zip"
    zip_path = DIST_DIR / zip_name

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    if zip_path.exists():
        zip_path.unlink()

    excluded_dirs  = {"__pycache__", ".git"}
    excluded_files = {".DS_Store", "Thumbs.db"}

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(BLENDER_SRC.rglob("*")):
            # Skip excluded dirs and their contents
            if any(part in excluded_dirs for part in file.parts):
                continue
            if file.name in excluded_files:
                continue
            if file.is_file():
                arcname = "ylos_blender" / file.relative_to(BLENDER_SRC)
                zf.write(file, arcname)

    print(f"  Built: {zip_path}  ({zip_path.stat().st_size // 1024} KB)")
    return zip_path


def build_houdini_package() -> Path:
    """
    Vendor ylos_core into ylos_houdini/pythonlibs/ and copy the package
    to dist/ylos_houdini/ ready for installation.

    Installation by the user:
      1. Copy dist/ylos_houdini/ somewhere permanent (e.g. ~/tools/ylos_houdini)
      2. Set YLOS_PIPELINE_PATH to that directory (in .bashrc or houdini.env)
      3. Copy ylos_houdini/packages/ylos_pipeline.json to
           $HOUDINI_USER_PREF_DIR/packages/
      4. Restart Houdini
    """
    houdini_src = REPO_ROOT / "ylos_houdini"
    if not houdini_src.exists():
        print("  ylos_houdini/ not found -- skipping.")
        return None

    # Vendor ylos_core into pythonlibs/
    vendor_dst = houdini_src / "pythonlibs" / "ylos_core"
    print(f"  Vendoring {CORE_SRC} -> {vendor_dst}")
    if vendor_dst.exists():
        shutil.rmtree(vendor_dst)
    shutil.copytree(CORE_SRC, vendor_dst)
    (vendor_dst.parent / "_VENDORED").write_text(
        "Auto-generated by build.py. Do not edit.\n"
    )

    # Copy package to dist/
    dist_houdini = DIST_DIR / "ylos_houdini"
    if dist_houdini.exists():
        shutil.rmtree(dist_houdini)
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    excluded_dirs = {"__pycache__", ".git"}
    shutil.copytree(
        houdini_src, dist_houdini,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
    )

    print(f"  Built: {dist_houdini}/")
    _print_houdini_install_instructions(dist_houdini)
    return dist_houdini


def _print_houdini_install_instructions(dist_houdini: Path) -> None:
    print(
        "\n  -- Houdini install instructions --\n"
        f"  1. Move {dist_houdini} somewhere permanent\n"
        f"     e.g.  mv {dist_houdini} ~/tools/ylos_houdini\n"
        f"\n"
        f"  2. Set YLOS_PIPELINE_PATH in $HOUDINI_USER_PREF_DIR/houdini.env:\n"
        f"     YLOS_PIPELINE_PATH = /Users/<you>/tools/ylos_houdini\n"
        f"\n"
        f"  3. Copy the package JSON:\n"
        f"     cp $YLOS_PIPELINE_PATH/packages/ylos_pipeline.json \\\n"
        f"        $HOUDINI_USER_PREF_DIR/packages/\n"
        f"\n"
        f"  4. Run create_hdas.py once from the Houdini Python Shell\n"
        f"     to generate the HDA files.\n"
        f"\n"
        f"  5. Restart Houdini.\n"
    )


def main():
    parser = argparse.ArgumentParser(description="Ylos Pipeline build script")
    parser.add_argument("--blender",  action="store_true", help="Build Blender zip only")
    parser.add_argument("--houdini",  action="store_true", help="Build Houdini package only")
    args = parser.parse_args()

    do_blender = args.blender or (not args.blender and not args.houdini)
    do_houdini = args.houdini or (not args.blender and not args.houdini)

    print("=== Ylos Pipeline Build ===")

    print("[1/2] Vendoring ylos_core...")
    vendor_core()

    if do_blender:
        print("[2/2] Building Blender zip...")
        zip_path = build_blender_zip()
        print(f"\nBlender addon ready: {zip_path}")
        print("Install via: Edit > Preferences > Add-ons > Install Legacy Add-on...")

    if do_houdini:
        print("[2/2] Building Houdini package...")
        houdini_result = build_houdini_package()
        if houdini_result:
            print(f"\nHoudini package ready: {houdini_result}")

    print("\nDone.")


if __name__ == "__main__":
    main()
